[project]
name = "skills"
version = "0.1.0"
description = ""
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "markdown>=3.10.1",
    "tokenizers>=0.15.0",
    "markdownify>=1.2.2",
]

[tool.setuptools]
py-modules = ["generate"]
packages = []
